title: Page par défaut

# TODO[panel]

layout: columns

columns:
  left:
    width: 2/3

    fields:
      text: fields/writer

  right:
    width: 1/3
    sections:
      files:
        type: files
        label: Photos
        layout: cards 
        image:
          cover: true
          ratio: 16/9
